image: node:16

pipelines:
  pull-requests:
    "**":
      - step:
          name: Docker builder & Upload
          deployment: Test
          script:
            - docker login harbor.secondev.com -u $HARBOR_USER -p $HARBOR_PASSWORD
            - docker build -t harbor.secondev.com/msa_project/statistics-service:latest .
            - docker tag harbor.secondev.com/msa_project/statistics-service:latest harbor.secondev.com/msa_project/statistics-service:0.1.$BITBUCKET_BUILD_NUMBER
            - docker push harbor.secondev.com/msa_project/statistics-service:latest

          services:
            - docker
          caches:
            - docker
      - step:
          name: 서버 스크립트 실행
          script:
            - ssh ss-devserver@secondev.com -p 2022 "sh /home/ss-devserver/secondspace-msa/statistics-service/docker.sh"
      - step:
          name: Slack Notification
          script:
            - pipe: atlassian/slack-notify:2.0.0
              variables:
                WEBHOOK_URL: $SLACK_WEBHOOK_URL
                MESSAGE: '"[${BITBUCKET_REPO_FULL_NAME}:${BITBUCKET_BUILD_NUMBER}] Build 성공 : staging"'
